# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bram Adams
tagline:             'Bramblings of a Madman'
description:         ''
url:                 http://bramses.github.io
baseurl:             ''
paginate:            4
gems:                [jekyll-paginate]
paginate_path:       "page:num"

# About/contact
author:
  name:              Bram Adams
  url:               http://bramses.github.io
  email:             ''

# Custom vars
version:             1.0.0
